Greeting.create(greeting: "Hello, Jacinta!")
Greeting.create(greeting: "Hello, Thomas!")
Greeting.create(greeting: "Hello, Peter!")
Greeting.create(greeting: "Hello, Utsargo!")
Greeting.create(greeting: "Hello, Prantosh!")